version: 2.1

orbs:
  sauce-connect: saucelabs/sauce-connect@1.0.1

workflows:
  browser_tests:
    jobs:
      - sauce-connect/with_proxy:
          name: Chrome Tests
          steps:
            - run: mvn verify -B -Dsauce.browser=chrome  -Dsauce.tunnel="chrome"
          tunnel_identifier: chrome
      - sauce-connect/with_proxy:
          name: Safari Tests
          steps:
            - run: mvn verify -B -Dsauce.browser=safari  -Dsauce.tunnel="safari"
          tunnel_identifier: safari